language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_script:
  - npm prune
after_success:
  - npm run publish-repo
  - npm run semantic-release
